{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gophprofile.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ required "secret.data.databaseURL is required when secret.create=true" .Values.secret.data.databaseURL | quote }}
  RABBITMQ_URL: {{ required "secret.data.rabbitmqURL is required when secret.create=true" .Values.secret.data.rabbitmqURL | quote }}
  S3_ACCESS_KEY: {{ required "secret.data.s3AccessKey is required when secret.create=true" .Values.secret.data.s3AccessKey | quote }}
  S3_SECRET_KEY: {{ required "secret.data.s3SecretKey is required when secret.create=true" .Values.secret.data.s3SecretKey | quote }}
  {{- with .Values.secret.extraData }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
